using System;
using System.Collections.Generic;
using System.Linq;
namespace Kingdom.EconomySimulation;
public static class ResearchSimulator
{
    public static void TryStart(SimulationState s,IReadOnlyList<Definition> defs){if(s.ActiveResearch!=null)return;var d=defs.Where(x=>!s.CompletedResearch.Contains(x.Id)&&((!x.AdvancesTechLevel&&x.TechLevel<=s.TechLevel)||(x.AdvancesTechLevel&&(int)x.TechLevel==(int)s.TechLevel+1))).Where(x=>x.Prerequisites.All(s.CompletedResearch.Contains)).Where(x=>ResourceSimulator.CanPay(s,x.ResourceRequirements)).OrderByDescending(x=>x.AdvancesTechLevel).ThenBy(x=>x.BaseCost).ThenBy(x=>x.Id,StringComparer.OrdinalIgnoreCase).FirstOrDefault();if(d==null){s.ResearchWaitingSeconds+=.1;return;}s.ActiveResearch=new ResearchTask{Definition=d,StartedSeconds=s.Seconds};s.Events.Add(new SimulationEvent{Seconds=s.Seconds,Kind="ResearchStarted",Id=d.Id,TechLevel=s.TechLevel});}
    public static void Tick(SimulationState s,IReadOnlyList<Definition> defs,IReadOnlyList<Definition> all)
    {var t=s.ActiveResearch;if(t==null){s.ResearchWaitingSeconds+=.1;return;}bool paid=true;foreach(var p in t.Definition.ResourceRequirements){double rem=p.Value-t.Paid.GetValueOrDefault(p.Key);double pay=Math.Min(rem,Math.Max(0,ResourceSimulator.Get(s,p.Key)));if(pay>0){ResourceSimulator.Add(s.Resources,p.Key,-pay);t.Paid[p.Key]=t.Paid.GetValueOrDefault(p.Key)+pay;}if(t.Paid.GetValueOrDefault(p.Key)+1e-9< p.Value)paid=false;}if(!paid){s.ResearchWaitingSeconds+=.1;return;}double rp=1;foreach(var b in all.Where(x=>x.Kind=="Building")){double mult=1;foreach(var e in CompletedEffects(s,13,b.Id))mult*=e.Value;rp+=s.Buildings.GetValueOrDefault(b.Id)*b.ResearchPower*mult;}double global=1;foreach(var e in CompletedEffects(s,4,""))global*=e.Value;double speed=rp*global*EraEffect(s.TechLevel,t.Definition.TechLevel)*.1;t.Progress+=speed;if(t.Progress<t.Definition.BaseCost)return;s.CompletedResearch.Add(t.Definition.Id);s.ActiveEffects.AddRange(t.Definition.Effects);s.Events.Add(new SimulationEvent{Seconds=s.Seconds,Kind="ResearchCompleted",Id=t.Definition.Id,TechLevel=s.TechLevel});if(t.Definition.AdvancesTechLevel){s.TechLevel=t.Definition.TechLevel;s.EraReachedMinute[s.TechLevel.ToString()]=(int)Math.Round(s.Seconds/60);}s.ActiveResearch=null;}
    private static IEnumerable<SimEffect> CompletedEffects(SimulationState s,int type,string target){return s.ActiveEffects.Where(e=>e.Type==type&&(string.IsNullOrEmpty(e.Target)||e.Target.Equals(target,StringComparison.OrdinalIgnoreCase)));}
    private static double EraEffect(SimTechLevel current,SimTechLevel target)=>current==target?1:1/(Math.Abs((int)target-(int)current)+.5);
}
