using System;using System.Collections.Generic;using System.IO;using System.Linq;using System.Text;
namespace Kingdom.EconomySimulation;
public static class BalanceAnalysis
{
 public static void Analyze(SimulationResult r,IReadOnlyList<Definition> defs,IReadOnlyList<Definition> b,IReadOnlyList<Definition> q){var s=r.State;foreach(var d in b.Where(x=>s.Buildings.ContainsKey(x.Id))){foreach(var o in d.Generation.Keys){double c=b.Where(x=>s.Buildings.ContainsKey(x.Id)).Sum(x=>x.Consumption.GetValueOrDefault(o)*s.Buildings.GetValueOrDefault(x.Id));if(c>0&&d.Generation[o]/c>10)Warn(r,"Economy explosion",o,$"{d.Id} output/active demand ratio exceeds 10.","High","Reduce multiplier or add sinks.");}foreach(var o in d.Consumption.Keys)if(b.Count(x=>x.Generation.ContainsKey(o))==1)Warn(r,"Single point bottleneck",o,$"Only one defined producer serves {d.Id}.","Medium","Add an alternative producer or move the dependency later.");}foreach(var d in b){double cost=d.ResourceRequirements.Values.Sum();double flow=b.Where(x=>s.Buildings.ContainsKey(x.Id)).Sum(x=>x.Generation.Values.Sum());if(cost>Math.Max(1,flow)*600)Warn(r,"Building unreachable by economy",d.Id,$"Construction inputs {cost:0.##} exceed ten minutes of active production.","Medium","Adjust cost or unlock a producer earlier.");}foreach(var d in q)foreach(var c in d.ResourceRequirements.Keys){int producers=b.Count(x=>x.Generation.ContainsKey(c));if(c.Equals("WoodLog",StringComparison.OrdinalIgnoreCase))producers++;if(producers==0)Warn(r,"Missing producer",c,$"Research {d.Id} requires a resource with no producer.","High","Add a reachable producer or remove the requirement.");}r.Bottlenecks.AddRange(b.Where(x=>s.Buildings.ContainsKey(x.Id)).SelectMany(x=>x.Consumption.Keys).Distinct(StringComparer.OrdinalIgnoreCase).Where(x=>b.Count(y=>y.Generation.ContainsKey(x))==1).Select(x=>$"{x}: single producer"));}
 private static void Warn(SimulationResult r,string t,string o,string reason,string sev,string sug){if(r.Warnings.Any(x=>x.Type==t&&x.Object==o))return;r.Warnings.Add(new BalanceWarning{Type=t,Object=o,Reason=reason,Severity=sev,Suggestion=sug});}
}
public static class SimulationReportWriter
{
 public static void Write(string root,IReadOnlyList<Definition> defs,SimulationResult r){Directory.CreateDirectory(root);File.WriteAllText(Path.Combine(root,"EconomySimulationReport.md"),Md(defs,r),new UTF8Encoding(false));File.WriteAllText(Path.Combine(root,"SimulationTimeline.csv"),Timeline(r.State),new UTF8Encoding(false));File.WriteAllText(Path.Combine(root,"BalanceWarnings.csv"),Warnings(r.Warnings),new UTF8Encoding(false));File.WriteAllText(Path.Combine(root,"ResourceFlowByEra.csv"),Flows(defs,r),new UTF8Encoding(false));File.WriteAllText(Path.Combine(root,"ResearchCompletionTimeline.csv"),Events(r,"ResearchCompleted","ResearchId"),new UTF8Encoding(false));File.WriteAllText(Path.Combine(root,"BuildingConstructionTimeline.csv"),Events(r,"BuildingCompleted","BuildingId"),new UTF8Encoding(false));}
 private static string Md(IReadOnlyList<Definition> d,SimulationResult r){var s=r.State;var b=new StringBuilder($"# Economy Simulation Report - {r.Route}\n\n");b.AppendLine("Offline runtime-aligned simulation; no Unity runtime was launched.");b.AppendLine("\n## Rules\n\n- Fixed 0.1 second ticks, minute aggregation, stockpiles clamp at zero.\n- Research cost is paid progressively; research speed uses ResearchPower and runtime era effect.\n- Buildings can repeat and use geometric cost growth; construction is immediate after payment.\n");foreach(var e in new[]{SimTechLevel.Animal,SimTechLevel.Neolithic,SimTechLevel.Medieval,SimTechLevel.Industrial}){int m=s.EraReachedMinute.GetValueOrDefault(e.ToString(),-1);b.AppendLine($"\n# {e} Age\n\n预计时间: {(m<0?"不可达":m+"分钟")}\n");var ev=s.Events.Where(x=>x.Kind=="ResearchCompleted"&&x.TechLevel==e).ToList();b.AppendLine($"研究完成数: {ev.Count}; 资源归零时间: {s.ZeroSeconds/60:0.##} 分钟。");}b.AppendLine("\n## Bottlenecks\n\n"+(r.Bottlenecks.Count==0?"None":string.Join("\n",r.Bottlenecks.Select(x=>"- "+x))));b.AppendLine("\n## Warnings\n\n"+(r.Warnings.Count==0?"None":string.Join("\n",r.Warnings.Select(x=>$"- **{x.Severity} {x.Type}** {x.Object}: {x.Reason} Suggestion: {x.Suggestion}"))));b.AppendLine("\n## Validation boundary\n\n未执行真实 Unity 编译。\n\n未执行 Huawei P40 Pro 真机验收。");return b.ToString();}
 private static string Timeline(SimulationState s){var b=new StringBuilder("Minute,TechLevel,Resources,Buildings,ResearchCompleted\n");foreach(var x in s.Timeline)b.AppendLine($"{x.Minute},{x.TechLevel},{Csv(x.Resources)},{Csv(x.Buildings)},{Csv(x.ResearchCompleted)}");return b.ToString();}
 private static string Events(SimulationResult r,string kind,string name){var b=new StringBuilder($"TimeSeconds,Minute,TechLevel,{name},Count\n");foreach(var e in r.State.Events.Where(x=>x.Kind==kind))b.AppendLine($"{e.Seconds:0.0},{e.Seconds/60:0.##},{e.TechLevel},{Csv(e.Id)},{e.Count}");return b.ToString();}
 private static string Flows(IReadOnlyList<Definition> defs,SimulationResult r){var b=new StringBuilder("Era,Resource,ProductionPerSecond,ConsumptionPerSecond,NetPerSecond\n");foreach(var era in Enum.GetValues<SimTechLevel>().Where(x=>x<=SimTechLevel.Industrial))foreach(var res in defs.Where(x=>x.Kind=="Resource").Select(x=>x.Id).Distinct(StringComparer.OrdinalIgnoreCase)){double p=0,c=0;foreach(var d in defs.Where(x=>x.Kind=="Building"&&x.TechLevel<=era)){int n=r.State.Buildings.GetValueOrDefault(d.Id);p+=d.Generation.GetValueOrDefault(res)*n;c+=d.Consumption.GetValueOrDefault(res)*n;}b.AppendLine($"{era},{Csv(res)},{p:0.###},{c:0.###},{p-c:0.###}");}return b.ToString();}
 private static string Warnings(IEnumerable<BalanceWarning> w){var b=new StringBuilder("Type,Object,Reason,Severity,Suggestion\n");foreach(var x in w)b.AppendLine(string.Join(",",Csv(x.Type),Csv(x.Object),Csv(x.Reason),Csv(x.Severity),Csv(x.Suggestion)));return b.ToString();}
 private static string Csv(string v)=>"\""+v.Replace("\"","\"\"").Replace("\r"," ").Replace("\n"," ")+"\"";
}
