[CmdletBinding()]
param([string]$ProjectRoot=(Join-Path $PSScriptRoot '..\..\Kingdom'),[string]$OutputPath=(Join-Path $PSScriptRoot '..\..\data\content-dependency\content-dependency-analysis.md'))
$ErrorActionPreference='Stop'; $assetRoot=Join-Path $ProjectRoot 'Assets\Resources\Datas'; $guidToId=@{}; $defs=@{}
function LoadDefs([string]$kind){foreach($f in Get-ChildItem (Join-Path $assetRoot $kind) -Recurse -Filter '*.asset'){$t=Get-Content $f.FullName -Raw;$i=[regex]::Match($t,'(?m)^[ \t]*id:\s*(\S+)\s*$');$m=Get-Content ($f.FullName+'.meta') -Raw;$g=[regex]::Match($m,'(?m)^guid:\s*(\S+)\s*$');if($i.Success -and $g.Success){$script:guidToId[$g.Groups[1].Value]=$i.Groups[1].Value;$script:defs[$i.Groups[1].Value]=[pscustomobject]@{Id=$i.Groups[1].Value;Kind=$kind;Text=$t}}}}
LoadDefs 'Resource';LoadDefs 'Building';LoadDefs 'Research'
function F([object]$d,[string]$n){$m=[regex]::Match($d.Text,"(?ms)^[ \t]*${n}:[ \t]*\r?\n(.*?)(?=^[ \t]*[A-Za-z][A-Za-z0-9_]*:[ \t]*|\z)");if(!$m.Success){return @()};return @([regex]::Matches($m.Value,'guid:\s*([0-9a-f]+)')|%{$guidToId[$_.Groups[1].Value]}|?{$_})}
function T([object]$d){$m=[regex]::Match($d.Text,'(?m)^[ \t]*TechLevel:\s*(\d+)');if($m.Success){return [int]$m.Groups[1].Value};return 0}
function A([object]$d){$m=[regex]::Match($d.Text,'(?m)^[ \t]*AdvancesTechLevel:\s*(\d+)');return $m.Success -and $m.Groups[1].Value -eq '1'}
function All([string[]]$ids,[hashtable]$set){foreach($id in $ids){if(!$set.ContainsKey($id)){return $false}};return $true}
$research=@($defs.Values|? { $_.Kind -eq 'Research' });$buildings=@($defs.Values|? { $_.Kind -eq 'Building' });$producers=@{}
foreach($b in $buildings){foreach($r in F $b resourceGenerationRates){if(!$producers.ContainsKey($r)){$producers[$r]=@()};$producers[$r]+=$b}}
$done=@{};$resources=@{WoodLog=$true};$built=@{};$tech=0;$changed=$true
while($changed){$changed=$false;foreach($r in $research){if($done.ContainsKey($r.Id)){continue};if((T $r)-gt $tech -and -not((A $r)-and (T $r)-eq $tech+1)){continue};if(!(All (F $r prerequisites) $done)){continue};if(!(All (F $r resourceRequirements) $resources)){continue};$done[$r.Id]=$true;if((A $r)-and (T $r)-gt $tech){$tech=T $r};$changed=$true};foreach($b in $buildings){if($built.ContainsKey($b.Id)-or (T $b)-gt $tech){continue};if(!(All (F $b requiredResearch) $done)){continue};if(!(All (F $b resourceRequirements) $resources)){continue};$built[$b.Id]=$true;foreach($r in F $b resourceGenerationRates){$resources[$r]=$true};$changed=$true}}
function Missing([string]$id){$x=@("Missing resource: $id");if(!$producers.ContainsKey($id)){return ($x+'Required producer: <none>')-join "`n"};foreach($b in $producers[$id]){$x+="Required producer: $($b.Id)";foreach($r in F $b requiredResearch){if(!$done.ContainsKey($r)){$x+="Producer blocked by: $r"}};foreach($c in F $b resourceRequirements){if(!$resources.ContainsKey($c)){$x+="Producer cost blocked by: $c"}}};return $x-join "`n"}
function Reason([object]$d,[string]$rf){foreach($r in F $d $rf){if(!$done.ContainsKey($r)){return "Missing prerequisite: $r"}};foreach($r in F $d resourceRequirements){if(!$resources.ContainsKey($r)){return Missing $r}};return "TechLevel condition: $(T $d)"}
$ur=@($research|?{!$done.ContainsKey($_.Id)}|%{[pscustomobject]@{Id=$_.Id;Reason=(Reason $_ prerequisites)}});$ub=@($buildings|?{!$built.ContainsKey($_.Id)}|%{[pscustomobject]@{Id=$_.Id;Reason=(Reason $_ requiredResearch)}})
$cycles=@();function Visit([object]$d,[hashtable]$vis,[hashtable]$seen,[Collections.ArrayList]$path){if($seen.ContainsKey($d.Id)){return};if($vis.ContainsKey($d.Id)){$s=$path.IndexOf($d.Id);if($s-lt 0){$s=0};$cycles+=(($path[$s..($path.Count-1)]+$d.Id)-join ' -> ');return};$vis[$d.Id]=$true;[void]$path.Add($d.Id);foreach($r in F $d prerequisites){if($defs.ContainsKey($r)){Visit $defs[$r] $vis $seen $path}};[void]$path.RemoveAt($path.Count-1);$vis.Remove($d.Id);$seen[$d.Id]=$true}
$vis=@{};$seen=@{};$path=[Collections.ArrayList]@();foreach($r in $research){Visit $r $vis $seen $path}
$dead=@();foreach($r in $research){foreach($x in F $r resourceRequirements){if($x -eq 'WoodLog'){continue};if($producers.ContainsKey($x)){foreach($b in $producers[$x]){if((F $b requiredResearch)-contains $r.Id){$dead+="$($r.Id) -> requires $x -> producer $($b.Id) requires $($r.Id)"}}}}};foreach($b in $buildings){foreach($x in F $b resourceRequirements){if($x -eq 'WoodLog'){continue};if($producers.ContainsKey($x)-and $producers[$x].Count-eq 1-and $producers[$x][0].Id-eq $b.Id){$dead+="$($b.Id) -> construction requires $x -> produced only by $($b.Id)"}}}
$o=[Text.StringBuilder]::new();[void]$o.AppendLine('# Content dependency analysis');[void]$o.AppendLine('================================');[void]$o.AppendLine('UNREACHABLE RESEARCH');[void]$o.AppendLine('================================');if(!$ur.Count){[void]$o.AppendLine('None')}else{foreach($x in $ur){[void]$o.AppendLine("`nResearch: $($x.Id)`nBlocked reason:`n$($x.Reason)")}};[void]$o.AppendLine("`n================================`nUNREACHABLE BUILDINGS`n================================");if(!$ub.Count){[void]$o.AppendLine('None')}else{foreach($x in $ub){[void]$o.AppendLine("`nBuilding: $($x.Id)`nBlocked reason:`n$($x.Reason)")}};[void]$o.AppendLine("`n================================`nRESOURCE DEADLOCKS`n================================");if(!$dead.Count){[void]$o.AppendLine('None')}else{$dead|%{[void]$o.AppendLine($_)}};[void]$o.AppendLine("`n================================`nRESEARCH CYCLES`n================================");if(!$cycles.Count){[void]$o.AppendLine('None')}else{$cycles|%{[void]$o.AppendLine($_)}}
$rs=if(!$ur.Count){'ALL'}else{'NO'};$bs=if(!$ub.Count){'ALL'}else{'NO'};$ds=if(!$dead.Count){'None'}else{'FOUND'};$cs=if(!$cycles.Count){'None'}else{'FOUND'};[void]$o.AppendLine("`nSummary`nDefinitions: $($defs.Count)`nResearch definitions: $($research.Count)`nBuilding definitions: $($buildings.Count)`nResearch reachable: $rs`nBuilding reachable: $bs`nResource deadlock: $ds`nResearch cycle: $cs`nHighest TechLevel: $tech");New-Item (Split-Path $OutputPath) -ItemType Directory -Force|Out-Null;[IO.File]::WriteAllText($OutputPath,$o.ToString(),[Text.UTF8Encoding]::new($false));$o.ToString()
$rs=if(!$ur.Count){'ALL'}else{'NO'};$bs=if(!$ub.Count){'ALL'}else{'NO'};$ds=if(!$dead.Count){'None'}else{'FOUND'};$cs=if(!$cycles.Count){'None'}else{'FOUND'};[void]$o.AppendLine("`n================================`nREPAIR SUGGESTIONS`n================================");if(!$dead.Count){[void]$o.AppendLine('None')}else{foreach($d in $dead){[void]$o.AppendLine("`nProblem:`n$d`n`nPossible fixes:`nOption A: Remove the blocking resource from the research or construction cost.`nOption B: Change the producer requiredResearch or constructionCost.`nOption C: Add an alternative producer reachable before the blocked node.")}};[void]$o.AppendLine("`nSummary`nDefinitions: $($defs.Count)`nResearch definitions: $($research.Count)`nBuilding definitions: $($buildings.Count)`nResearch reachable: $rs`nBuilding reachable: $bs`nResource deadlock: $ds`nResearch cycle: $cs`nHighest TechLevel: $tech");New-Item (Split-Path $OutputPath) -ItemType Directory -Force|Out-Null;[IO.File]::WriteAllText($OutputPath,$o.ToString(),[Text.UTF8Encoding]::new($false));$o.ToString()
